### ISSUE TITLE
Kube 1.22 API deprecations

### ISSUE THREAD

**Issue by mciverza** [lsdopen/charts#32]
Current subcharts that are consumed make use of the following Ingress API: "Ingress" in version "extensions/v1beta1
which is removed in Kubernetes 1.22.

as per chart: 1.0.0-SNAPSHOT, from develop branch

commit f3c86f41175acbf99faa048d28c069c8c13fa182 (HEAD -> develop, origin/develop)

**Chart.yaml**
```
apiVersion: v2
name: ahoy
version: '1.0.0-SNAPSHOT'
dependencies:
  - name: postgresql
    version: "8.10.4"
    repository: "https://charts.bitnami.com/bitnami"
  - name: keycloak
    condition: keycloak.install
    version: "9.0.1"
    repository: "https://codecentric.github.io/helm-charts"
  - name: argo-cd
    condition: argo-cd.install
    version: "2.14.7"
    repository: "https://argoproj.github.io/argo-helm"
  - name: sealed-secrets
    condition: sealed-secrets.install
    version: "1.15.0-r1"
    repository: "https://bitnami-labs.github.io/sealed-secrets"
```

for example argo-cd
```
apiVersion: networking.k8s.io/v1beta1
```
